import { PdfDocument, PdfError, type PdfFont } from './document'
import { tokenise, type PdfToken } from './lexer'

// Text with positions. A bank statement is a table, and a table is only a table
// because of where things sit: the difference between "paid in" and "paid out"
// is one column, and any reading that throws the coordinates away has thrown
// away the only thing that tells those two apart.

export type PdfTextItem = {
  page: number
  /** Page coordinates, in points, origin bottom-left as PDF has it. */
  x: number
  y: number
  size: number
  text: string
}

export type PdfTextRow = {
  page: number
  y: number
  cells: PdfTextItem[]
}

type Matrix = [number, number, number, number, number, number]

const IDENTITY: Matrix = [1, 0, 0, 1, 0, 0]

function multiply(a: Matrix, b: Matrix): Matrix {
  return [
    a[0] * b[0] + a[1] * b[2],
    a[0] * b[1] + a[1] * b[3],
    a[2] * b[0] + a[3] * b[2],
    a[2] * b[1] + a[3] * b[3],
    a[4] * b[0] + a[5] * b[2] + b[4],
    a[4] * b[1] + a[5] * b[3] + b[5],
  ]
}

/**
 * A kern wide enough to be a space.
 *
 * A TJ array's numbers nudge the next glyph left by thousandths of an em. Small
 * ones are kerning between letters; a large one is how a generator writes a
 * space without writing a space, and a statement whose description arrives as
 * "AMAZONUK*G24YU16C5" is no use to anybody.
 */
const SPACE_KERN = 200

function decode(font: PdfFont | undefined, bytes: string): string {
  if (!font?.toUnicode) {
    // A two-byte font with no ToUnicode map is genuinely undecodable: the codes
    // are the font's own glyph indices and mean nothing without the map, so
    // anything printed here would be invented.
    if (font?.twoByte) return ''
    // A one-byte font is a different matter. Its codes are an ordinary character
    // encoding - WinAnsi, MacRoman, Standard - and all three agree with latin1
    // across the printable ASCII range, which is the whole of what a bank
    // statement is made of. Returning nothing here was wrong twice over: it lost
    // the text, and it made the reader report a perfectly readable PDF as a
    // scan.
    return bytes
  }
  let out = ''
  if (font.twoByte) {
    for (let i = 0; i + 1 < bytes.length; i += 2) {
      out += font.toUnicode.get((bytes.charCodeAt(i) << 8) | bytes.charCodeAt(i + 1)) ?? ''
    }
  } else {
    for (const character of bytes) {
      out += font.toUnicode.get(character.charCodeAt(0)) ?? character
    }
  }
  return out
}

function extractPage(tokens: PdfToken[], fonts: Map<string, PdfFont>, page: number): PdfTextItem[] {
  const items: PdfTextItem[] = []

  let textMatrix: Matrix = [...IDENTITY]
  let lineMatrix: Matrix = [...IDENTITY]
  let graphicsMatrix: Matrix = [...IDENTITY]
  const graphicsStack: Matrix[] = []
  let fontName: string | null = null
  let fontSize = 0
  let leading = 0

  const operands: PdfToken[] = []

  const emit = (text: string): void => {
    if (!text.trim()) return
    // The text matrix is relative to the graphics state, so a page that has been
    // translated or scaled as a whole - which a statement generated by pouring
    // one layout into another routinely has been - still reports true positions.
    const placed = multiply(textMatrix, graphicsMatrix)
    items.push({ page, x: placed[4], y: placed[5], size: fontSize * Math.abs(placed[3] || 1), text })
  }

  const nextLine = (by: number): void => {
    lineMatrix = multiply([1, 0, 0, 1, 0, by], lineMatrix)
    textMatrix = [...lineMatrix]
  }

  for (const token of tokens) {
    if (token.t !== 'op') { operands.push(token); continue }
    // Array brackets must not clear the operand stack: the strings between them
    // are the TJ operator's arguments, and clearing on `]` loses every one.
    if (token.v === '[' || token.v === ']') continue

    const args = operands.splice(0)
    const numbers = args.filter((a): a is { t: 'num'; v: number } => a.t === 'num').map((a) => a.v)

    switch (token.v) {
      case 'q':
        graphicsStack.push([...graphicsMatrix])
        break
      case 'Q':
        graphicsMatrix = graphicsStack.pop() ?? [...IDENTITY]
        break
      case 'cm':
        if (numbers.length >= 6) graphicsMatrix = multiply(numbers.slice(-6) as Matrix, graphicsMatrix)
        break
      case 'BT':
        textMatrix = [...IDENTITY]
        lineMatrix = [...IDENTITY]
        break
      case 'Tf': {
        const name = args.find((a) => a.t === 'name')
        if (name && name.t === 'name') fontName = name.v
        fontSize = numbers[numbers.length - 1] ?? fontSize
        break
      }
      case 'TL':
        leading = numbers[0] ?? leading
        break
      case 'Tm':
        if (numbers.length >= 6) {
          lineMatrix = numbers.slice(-6) as Matrix
          textMatrix = [...lineMatrix]
        }
        break
      case 'Td':
        lineMatrix = multiply([1, 0, 0, 1, numbers[0] ?? 0, numbers[1] ?? 0], lineMatrix)
        textMatrix = [...lineMatrix]
        break
      case 'TD':
        leading = -(numbers[1] ?? 0)
        lineMatrix = multiply([1, 0, 0, 1, numbers[0] ?? 0, numbers[1] ?? 0], lineMatrix)
        textMatrix = [...lineMatrix]
        break
      case 'T*':
        nextLine(-leading)
        break
      case 'Tj':
        emit(decode(fonts.get(fontName ?? ''), args.filter((a) => a.t === 'str').map((a) => a.v).join('')))
        break
      case "'":
      case '"':
        nextLine(-leading)
        emit(decode(fonts.get(fontName ?? ''), args.filter((a) => a.t === 'str').map((a) => a.v).join('')))
        break
      case 'TJ': {
        const font = fonts.get(fontName ?? '')
        let text = ''
        for (const arg of args) {
          if (arg.t === 'str') text += decode(font, arg.v)
          else if (arg.t === 'num' && arg.v <= -SPACE_KERN && text && !text.endsWith(' ')) text += ' '
        }
        emit(text)
        break
      }
      default:
        break
    }
  }

  return items
}

/**
 * Group items into rows by their vertical position.
 *
 * The tolerance is a fraction of the text size rather than a fixed number of
 * points, because a statement's own footnotes are set several sizes smaller than
 * its table and a tolerance loose enough for one merges two lines of the other.
 */
export function groupIntoRows(items: PdfTextItem[]): PdfTextRow[] {
  // Page first. Sorting on y alone interleaves two pages wherever they happen to
  // put text at the same height - which, since every page of a statement is laid
  // out the same, is everywhere - and then no row ever gathers more than one
  // cell.
  const sorted = [...items].sort((a, b) => a.page - b.page || b.y - a.y || a.x - b.x)
  const rows: PdfTextRow[] = []

  for (const item of sorted) {
    const current = rows[rows.length - 1]
    const tolerance = Math.max(1.5, Math.min(item.size, 12) * 0.4)
    if (current && current.page === item.page && Math.abs(current.y - item.y) <= tolerance) {
      current.cells.push(item)
    } else {
      rows.push({ page: item.page, y: item.y, cells: [item] })
    }
  }

  for (const row of rows) row.cells.sort((a, b) => a.x - b.x)
  return rows
}

export type PdfText = {
  pageCount: number
  items: PdfTextItem[]
  rows: PdfTextRow[]
  /** Every row's text joined up, for the metadata scraping that does not care where things sit. */
  plain: string
}

export function extractPdfText(bytes: Buffer): PdfText {
  const document = new PdfDocument(bytes)
  const pages = document.pages()
  if (pages.length === 0) {
    throw new PdfError('We could not find any pages in that PDF.')
  }

  const items: PdfTextItem[] = []
  for (const page of pages) {
    items.push(...extractPage(tokenise(page.content), page.fonts, page.index))
  }

  if (items.length === 0) {
    throw new PdfError(
      'There is no readable text in that PDF - it looks like a scan or a photograph of a statement rather than one downloaded from the bank. Download the PDF from your online banking, or import a CSV instead.',
    )
  }

  const rows = groupIntoRows(items)
  return {
    pageCount: pages.length,
    items,
    rows,
    plain: rows.map((row) => row.cells.map((cell) => cell.text).join(' ')).join('\n'),
  }
}
