import { PdfDocument, PdfError, type PdfFont } from './document'
import { tokenise, type PdfToken } from './lexer'

// Text with positions. A bank statement is a table, and a table is only a table
// because of where things sit: the difference between "paid in" and "paid out"
// is one column, and any reading that throws the coordinates away has thrown
// away the only thing that tells those two apart.

export type PdfTextItem = {
  page: number
  /** Page coordinates, in points, origin bottom-left as PDF has it. */
  x: number
  y: number
  size: number
  text: string
  /**
   * How far along the line this item advances, in points. Zero where the font
   * declared no widths, which means "cannot measure" and never "no width".
   *
   * Only mergeGlyphRuns uses it, and it exists for one reason: a generator that
   * places every glyph with its own Td gives one item per letter, and the ONLY
   * thing that separates "Invoice number" from "Invoicenumber" is knowing how
   * wide an "e" is and seeing whether the next glyph starts further along.
   */
  width: number
}

export type PdfTextRow = {
  page: number
  y: number
  cells: PdfTextItem[]
}

type Matrix = [number, number, number, number, number, number]

const IDENTITY: Matrix = [1, 0, 0, 1, 0, 0]

function multiply(a: Matrix, b: Matrix): Matrix {
  return [
    a[0] * b[0] + a[1] * b[2],
    a[0] * b[1] + a[1] * b[3],
    a[2] * b[0] + a[3] * b[2],
    a[2] * b[1] + a[3] * b[3],
    a[4] * b[0] + a[5] * b[2] + b[4],
    a[4] * b[1] + a[5] * b[3] + b[5],
  ]
}

/**
 * A kern wide enough to be a space.
 *
 * A TJ array's numbers nudge the next glyph left by thousandths of an em. Small
 * ones are kerning between letters; a large one is how a generator writes a
 * space without writing a space, and a statement whose description arrives as
 * "AMAZONUK*G24YU16C5" is no use to anybody.
 */
const SPACE_KERN = 200

function decode(font: PdfFont | undefined, bytes: string): string {
  if (!font?.toUnicode) {
    // A two-byte font with no ToUnicode map is genuinely undecodable: the codes
    // are the font's own glyph indices and mean nothing without the map, so
    // anything printed here would be invented.
    if (font?.twoByte) return ''
    // A one-byte font is a different matter. Its codes are an ordinary character
    // encoding - WinAnsi, MacRoman, Standard - and all three agree with latin1
    // across the printable ASCII range, which is the whole of what a bank
    // statement is made of. Returning nothing here was wrong twice over: it lost
    // the text, and it made the reader report a perfectly readable PDF as a
    // scan.
    return bytes
  }
  let out = ''
  if (font.twoByte) {
    for (let i = 0; i + 1 < bytes.length; i += 2) {
      out += font.toUnicode.get((bytes.charCodeAt(i) << 8) | bytes.charCodeAt(i + 1)) ?? ''
    }
  } else {
    for (const character of bytes) {
      out += font.toUnicode.get(character.charCodeAt(0)) ?? character
    }
  }
  // A subset font routinely maps its spare glyphs to U+0000. That is the CMap
  // saying "no character", not a character - and a NUL carried into the text is
  // invisible on screen and matches nothing, which is the worst way to be wrong.
  return out.replace(/\u0000/g, '')
}

/** How far a run of character codes advances the line, in points. */
function advanceOf(font: PdfFont | undefined, bytes: string, size: number): number {
  if (!font || font.widths.size === 0) return 0
  let total = 0
  if (font.twoByte) {
    for (let i = 0; i + 1 < bytes.length; i += 2) {
      const code = (bytes.charCodeAt(i) << 8) | bytes.charCodeAt(i + 1)
      total += font.widths.get(code) ?? font.defaultWidth
    }
  } else {
    for (const character of bytes) {
      total += font.widths.get(character.charCodeAt(0)) ?? font.defaultWidth
    }
  }
  return (total / 1000) * size
}

function extractPage(tokens: PdfToken[], fonts: Map<string, PdfFont>, page: number): PdfTextItem[] {
  const items: PdfTextItem[] = []

  let textMatrix: Matrix = [...IDENTITY]
  let lineMatrix: Matrix = [...IDENTITY]
  let graphicsMatrix: Matrix = [...IDENTITY]
  const graphicsStack: Matrix[] = []
  let fontName: string | null = null
  let fontSize = 0
  let leading = 0

  const operands: PdfToken[] = []

  const emit = (text: string, advance = 0): void => {
    if (!text.trim()) return
    // The text matrix is relative to the graphics state, so a page that has been
    // translated or scaled as a whole - which a statement generated by pouring
    // one layout into another routinely has been - still reports true positions.
    const placed = multiply(textMatrix, graphicsMatrix)
    items.push({
      page,
      x: placed[4],
      y: placed[5],
      size: fontSize * Math.abs(placed[3] || 1),
      text,
      width: advance * Math.abs(placed[0] || 1),
    })
  }

  const nextLine = (by: number): void => {
    lineMatrix = multiply([1, 0, 0, 1, 0, by], lineMatrix)
    textMatrix = [...lineMatrix]
  }

  for (const token of tokens) {
    if (token.t !== 'op') { operands.push(token); continue }
    // Array brackets must not clear the operand stack: the strings between them
    // are the TJ operator's arguments, and clearing on `]` loses every one.
    if (token.v === '[' || token.v === ']') continue

    const args = operands.splice(0)
    const numbers = args.filter((a): a is { t: 'num'; v: number } => a.t === 'num').map((a) => a.v)

    switch (token.v) {
      case 'q':
        graphicsStack.push([...graphicsMatrix])
        break
      case 'Q':
        graphicsMatrix = graphicsStack.pop() ?? [...IDENTITY]
        break
      case 'cm':
        if (numbers.length >= 6) graphicsMatrix = multiply(numbers.slice(-6) as Matrix, graphicsMatrix)
        break
      case 'BT':
        textMatrix = [...IDENTITY]
        lineMatrix = [...IDENTITY]
        break
      case 'Tf': {
        const name = args.find((a) => a.t === 'name')
        if (name && name.t === 'name') fontName = name.v
        fontSize = numbers[numbers.length - 1] ?? fontSize
        break
      }
      case 'TL':
        leading = numbers[0] ?? leading
        break
      case 'Tm':
        if (numbers.length >= 6) {
          lineMatrix = numbers.slice(-6) as Matrix
          textMatrix = [...lineMatrix]
        }
        break
      case 'Td':
        lineMatrix = multiply([1, 0, 0, 1, numbers[0] ?? 0, numbers[1] ?? 0], lineMatrix)
        textMatrix = [...lineMatrix]
        break
      case 'TD':
        leading = -(numbers[1] ?? 0)
        lineMatrix = multiply([1, 0, 0, 1, numbers[0] ?? 0, numbers[1] ?? 0], lineMatrix)
        textMatrix = [...lineMatrix]
        break
      case 'T*':
        nextLine(-leading)
        break
      case 'Tj': {
        const font = fonts.get(fontName ?? '')
        const raw = args.filter((a) => a.t === 'str').map((a) => a.v).join('')
        emit(decode(font, raw), advanceOf(font, raw, fontSize))
        break
      }
      case "'":
      case '"': {
        nextLine(-leading)
        const font = fonts.get(fontName ?? '')
        const raw = args.filter((a) => a.t === 'str').map((a) => a.v).join('')
        emit(decode(font, raw), advanceOf(font, raw, fontSize))
        break
      }
      case 'TJ': {
        const font = fonts.get(fontName ?? '')
        let text = ''
        let advance = 0
        for (const arg of args) {
          if (arg.t === 'str') {
            text += decode(font, arg.v)
            advance += advanceOf(font, arg.v, fontSize)
          } else if (arg.t === 'num') {
            // A kern is a displacement in thousandths of an em, subtracted.
            advance -= (arg.v / 1000) * fontSize
            if (arg.v <= -SPACE_KERN && text && !text.endsWith(' ')) text += ' '
          }
        }
        emit(text, advance)
        break
      }
      default:
        break
    }
  }

  return items
}

/**
 * Group items into rows by their vertical position.
 *
 * The tolerance is a fraction of the text size rather than a fixed number of
 * points, because a statement's own footnotes are set several sizes smaller than
 * its table and a tolerance loose enough for one merges two lines of the other.
 */
export function groupIntoRows(items: PdfTextItem[]): PdfTextRow[] {
  // Page first. Sorting on y alone interleaves two pages wherever they happen to
  // put text at the same height - which, since every page of a statement is laid
  // out the same, is everywhere - and then no row ever gathers more than one
  // cell.
  const sorted = [...items].sort((a, b) => a.page - b.page || b.y - a.y || a.x - b.x)
  const rows: PdfTextRow[] = []

  for (const item of sorted) {
    const current = rows[rows.length - 1]
    const tolerance = Math.max(1.5, Math.min(item.size, 12) * 0.4)
    if (current && current.page === item.page && Math.abs(current.y - item.y) <= tolerance) {
      current.cells.push(item)
    } else {
      rows.push({ page: item.page, y: item.y, cells: [item] })
    }
  }

  for (const row of rows) row.cells.sort((a, b) => a.x - b.x)
  return rows
}

/** No visible gap at all: the two glyphs are inside one word. */
const JOIN_RATIO = 0.18
/** A gap about the width of a space: one word ends and the next begins. */
const WORD_RATIO = 0.9

/**
 * Put letters back into words.
 *
 * A great many generators - Stripe's invoices, anything printed through a
 * headless browser - position every single glyph with its own Td, so the page
 * arrives as six hundred one-character items and every naive reading of it says
 * "I n v o i c e". No pattern in this module survives that: a money regex
 * wanting two decimal places never sees "75.00", and a label list wanting
 * "subtotal" never sees anything but "s".
 *
 * The gap between two glyphs is where the next one STARTS less where the last
 * one ENDS, which is why the widths are parsed at all. A gap under a fifth of an
 * em is inside a word, a gap up to about an em is a space, and anything wider is
 * a different column and stays a different cell.
 *
 * A row whose items carry no measured width is returned untouched. That is the
 * safe direction: a font we could not measure leaves the page exactly as it
 * reads today rather than being guessed at.
 */
export function mergeGlyphRuns(rows: PdfTextRow[]): PdfTextRow[] {
  return rows.map((row) => {
    if (row.cells.length < 2) return row
    if (row.cells.some((cell) => !(cell.width > 0))) return row

    const merged: PdfTextItem[] = []
    let current: PdfTextItem = { ...row.cells[0]! }

    for (let index = 1; index < row.cells.length; index += 1) {
      const next = row.cells[index]!
      const em = Math.max(current.size, next.size)
      const gap = next.x - (current.x + current.width)
      if (gap > em * WORD_RATIO) {
        merged.push(current)
        current = { ...next }
        continue
      }
      const separator = gap > em * JOIN_RATIO && !current.text.endsWith(' ') ? ' ' : ''
      current = {
        ...current,
        text: current.text + separator + next.text,
        width: next.x + next.width - current.x,
      }
    }

    merged.push(current)
    return { ...row, cells: merged }
  })
}

/** Every row's text joined up again, after the cells have been merged. */
export function plainFromRows(rows: PdfTextRow[]): string {
  return rows.map((row) => row.cells.map((cell) => cell.text).join(' ')).join('\n')
}

export type PdfText = {
  pageCount: number
  items: PdfTextItem[]
  rows: PdfTextRow[]
  /** Every row's text joined up, for the metadata scraping that does not care where things sit. */
  plain: string
}

export function extractPdfText(bytes: Buffer): PdfText {
  const document = new PdfDocument(bytes)
  const pages = document.pages()
  if (pages.length === 0) {
    throw new PdfError('We could not find any pages in that PDF.')
  }

  const items: PdfTextItem[] = []
  for (const page of pages) {
    items.push(...extractPage(tokenise(page.content), page.fonts, page.index))
  }

  if (items.length === 0) {
    throw new PdfError(
      'There is no readable text in that PDF - it looks like a scan or a photograph of a statement rather than one downloaded from the bank. Download the PDF from your online banking, or import a CSV instead.',
    )
  }

  const rows = groupIntoRows(items)
  return {
    pageCount: pages.length,
    items,
    rows,
    plain: rows.map((row) => row.cells.map((cell) => cell.text).join(' ')).join('\n'),
  }
}
